### ISSUE TITLE
NullPointerException in SyncingSqlTopComponent

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [cismet/abf#58]
``java.lang.NullPointerException
	at de.cismet.cids.abf.domainserver.project.sync.SyncingSqlTopComponent.<init>(SyncingSqlTopComponent.java:74)
	at de.cismet.cids.abf.domainserver.project.nodes.SyncManagement$5.run(SyncManagement.java:584)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at org.netbeans.core.windows.services.NbPresenter.superShow(NbPresenter.java:1065)
	at org.netbeans.core.windows.services.NbPresenter.doShow(NbPresenter.java:1115)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:1087)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:128)
	at org.openide.util.Mutex.doEventAccess(Mutex.java:1376)
	at org.openide.util.Mutex.readAccess(Mutex.java:278)
	at org.netbeans.core.windows.services.NbPresenter.show(NbPresenter.java:1072)
	at java.awt.Component.show(Component.java:1673)
	at java.awt.Component.setVisible(Component.java:1625)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at de.cismet.cids.abf.utilities.windows.ErrorUtils$1.run(ErrorUtils.java:83)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused: java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1319)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1294)
	at de.cismet.cids.abf.domainserver.project.nodes.SyncManagement.getTopComponent(SyncManagement.java:580)
Caused: java.lang.IllegalStateException: could no create syncing top component
	at de.cismet.cids.abf.domainserver.project.nodes.SyncManagement.getTopComponent(SyncManagement.java:590)
	at de.cismet.cids.abf.domainserver.project.nodes.SyncManagement$3.run(SyncManagement.java:373)
[catch] at java.lang.Thread.run(Thread.java:745)
``

**Comment by p-a-s-c-a-l** [comment]
could not check for locks:
``java.util.concurrent.TimeoutException       at java.util.concurrent.FutureTask.get(FutureTask.java:205)       at de.cismet.cids.abf.domainserver.DeleteLockAction.lockExists(DeleteLockAction.java:157)       at de.cismet.cids.abf.domainserver.DeleteLockAction.enable(DeleteLockAction.java:133)       at org.openide.util.actions.NodeAction$DelegateAction.resultChanged(NodeAction.java:615)       at org.openide.util.actions.NodeAction$DelegateAction.<init>(NodeAction.java:560)       at org.openide.util.actions.NodeAction.createContextAwareInstance(NodeAction.java:357)       at org.openide.util.Utilities.actionsToPopup(Utilities.java:2832)       at org.openide.util.Utilities.actionsToPopup(Utilities.java:2928)       at org.openide.explorer.view.TreeView.createPopup(TreeView.java:1058)       at org.openide.explorer.view.TreeView$PopupAdapter.showPopup(TreeView.java:1555)       at org.openide.awt.MouseUtils$PopupMouseAdapter.maybePopup(MouseUtils.java:189)       at org.openide.awt.MouseUtils$PopupMouseAdapter.mouseReleased(MouseUtils.java:184)       at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)       at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)       at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)       at java.awt.Component.processMouseEvent(Component.java:6535)       at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)       at java.awt.Component.processEvent(Component.java:6300)       at java.awt.Container.processEvent(Container.java:2236)       at java.awt.Component.dispatchEventImpl(Component.java:4891)       at java.awt.Container.dispatchEventImpl(Container.java:2294)       at java.awt.Component.dispatchEvent(Component.java:4713)       at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)       at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)       at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)       at java.awt.Container.dispatchEventImpl(Container.java:2280)       at java.awt.Window.dispatchEventImpl(Window.java:2750)       at java.awt.Component.dispatchEvent(Component.java:4713)       at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)       at java.awt.EventQueue.access$500(EventQueue.java:97)       at java.awt.EventQueue$3.run(EventQueue.java:709)       at java.awt.EventQueue$3.run(EventQueue.java:703)       at java.security.AccessController.doPrivileged(Native Method)       at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)       at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)       at java.awt.EventQueue$4.run(EventQueue.java:731)       at java.awt.EventQueue$4.run(EventQueue.java:729)       at java.security.AccessController.doPrivileged(Native Method)       at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)       at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)       at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)       at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)       at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)       at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)       at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)       at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)       at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) ``

**Comment by p-a-s-c-a-l** [comment]
``javax.persistence.PersistenceException: org.hibernate.TransactionException: JDBC commit failed

STACKTRACE:
org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1235)
org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1168)
org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:81)
de.cismet.cids.jpa.backend.core.PersistenceInterceptor.cleanup(PersistenceInterceptor.java:186)
de.cismet.cids.jpa.backend.core.PersistenceInterceptor.invoke(PersistenceInterceptor.java:79)
net.sf.tie.StackInvocation.proceed(StackInvocation.java:95)
net.sf.tie.ProxyHandler.invoke(ProxyHandler.java:56)
com.sun.proxy.$Proxy48.close(Unknown Source)
de.cismet.cids.jpa.backend.service.impl.BackendImpl.close(BackendImpl.java:276)
de.cismet.cids.abf.domainserver.ReadCacheBackend.close(ReadCacheBackend.java:399)
de.cismet.cids.abf.domainserver.project.DomainserverProject.setConnected(DomainserverProject.java:608)
de.cismet.cids.abf.domainserver.project.DomainserverProjectNode$ProjectCloseHookAction.actionPerformed(DomainserverProjectNode.java:332)
javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
javax.swing.AbstractButton.doClick(AbstractButton.java:376)
javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
java.awt.Component.processMouseEvent(Component.java:6535)
javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
java.awt.Component.processEvent(Component.java:6300)
java.awt.Container.processEvent(Container.java:2236)
java.awt.Component.dispatchEventImpl(Component.java:4891)
java.awt.Container.dispatchEventImpl(Container.java:2294)
java.awt.Component.dispatchEvent(Component.java:4713)
java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
java.awt.Container.dispatchEventImpl(Container.java:2280)
java.awt.Window.dispatchEventImpl(Window.java:2750)
java.awt.Component.dispatchEvent(Component.java:4713)
java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
java.awt.EventQueue.access$500(EventQueue.java:97)
java.awt.EventQueue$3.run(EventQueue.java:709)
java.awt.EventQueue$3.run(EventQueue.java:703)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
java.awt.EventQueue$4.run(EventQueue.java:731)
java.awt.EventQueue$4.run(EventQueue.java:729)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
``
