### ISSUE TITLE
Possible to open Catalogue when disconnected

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [cismet/abf#60]
When disconnected, opening catalogue root node  throws an exception:

![abf-bug](https://cloud.githubusercontent.com/assets/1788226/10962551/655f8aa2-8399-11e5-8dc0-b12129851df8.png)

` java.lang.NullPointerException       at de.cismet.cids.abf.domainserver.project.nodes.CatalogManagement$CatalogNodeManagementChildren.threadedNotify(CatalogManagement.java:292)       at de.cismet.cids.abf.domainserver.project.ProjectChildren$2.run(ProjectChildren.java:114)       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)       at java.util.concurrent.FutureTask.run(FutureTask.java:266)       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)       at java.lang.Thread.run(Thread.java:745)
` 

`
 java.util.MissingResourceException: Can't find resource for bundle org.openide.util.NbBundle$PBundle, key NavigatorNodeManagementChildren.addNotify().t.run().exc       at java.util.ResourceBundle.getObject(ResourceBundle.java:450)       at java.util.ResourceBundle.getString(ResourceBundle.java:407)       at org.openide.util.NbBundle.getMessage(NbBundle.java:642)       at de.cismet.cids.abf.domainserver.project.nodes.CatalogManagement$CatalogNodeManagementChildren.threadedNotify(CatalogManagement.java:305)       at de.cismet.cids.abf.domainserver.project.ProjectChildren$2.run(ProjectChildren.java:114)       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)       at java.util.concurrent.FutureTask.run(FutureTask.java:266)       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)       at java.lang.Thread.run(Thread.java:745)
`

**Comment by helllth** [comment]
will split that bug into 2:
1. this one: When disconnected: catalog should not have any children
2. the missing resource exception --> #61
